tigrmanagr/models/board.py
from sqlalchemy import Column, ForeignKey, String, Integer
from sqlalchemy.orm import relationship
from tigrmanagr.db import Base

class Board(Base):
    __tablename__ = 'boards'
    board_id = Column(Integer, primary_key=True)
    board_name = Column(String(200), nullable=False)


    

tigrmanagr/controllers/board.py
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, jsonify, session
from functools import wraps


import tigrmanagr.services.todo as svc_todo
import tigrmanagr.services.board as svc_board

bp = Blueprint('board', __name__, url_prefix='/board')

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        user = dict(session).get('profile', None)

        if user:
            return f(*args, **kwargs)
        return redirect('/login')
    return decorated_function

@bp.route('/')
@login_required
def home():
    boards, error = svc_board.get_all()
    if error:
        flash(error)
    email = dict(session)['profile']['email']
    return render_template('board/index.html', email=email, boards=boards)

@bp.route('/<int:board_id>')
@login_required
def boardSpace(board_id):
   todos, error = svc_board.get_todo(board_id)
   boards, error = svc_board.get_all()
   board, error = svc_board.get_by_id(board_id)
   if error:
       flash(error)
   email = dict(session)['profile']['email']
   return render_template('board/read.html', todos=todos, email=email, boards=boards, board=board)

@bp.route('/<int:board_id>/create', methods=['GET', 'POST'])
@login_required
def createTodo(board_id):
    error = ''
    board, error = svc_board.get_by_id(board_id)
    if request.method == 'POST':
        data = request.get_json() or {}
        
        if data.get('todo_title') and data.get('board_id'):
            todo_title = data.get('todo_title', '')
            board_id = data.get('board_id', '')

            todo_title = todo_title.strip()

            data = {
                'todo_title': todo_title,
                'board_id': int(board_id)
            }
            _,error = svc_todo.create(data)
            if not error:
                return jsonify({'status': 200, 'message': 'Success', 'redirect': '/board'})

    if error:
        return jsonify({'status': 500, 'message': 'Error'})
    return render_template('todo/create.html', board=board)

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def createBoard():
    error = ''
    if request.method == 'POST':
        data = request.get_json() or {}
        
        if data.get('board_name'):
            board_name = data.get('board_name', '')

            board_name = board_name.strip()

            data = {
                'board_name': board_name,
            }
            _,error = svc_board.create(data)
            if not error:
                return jsonify({'status': 200, 'message': 'Success', 'redirect': '/board'})

    if error:
        return jsonify({'status': 500, 'message': 'Error'})
    return render_template('board/create.html')

@bp.route('/edit/<int:board_id>', methods=['GET', 'POST'])
@login_required
def edit(board_id):
    error = ''
    board, error = svc_board.get_by_id(board_id)

    if request.method == 'POST':

        data = request.get_json() or {}

        if data.get('board_id') and data.get('name_update'):
            board_id = data.get('board_id', '')
            name_update = data.get('name_update', '')
                                                    
            name_update = name_update.strip()


            data = {
                'board_id': int(board_id),
                'board_name': name_update,
            }
            _,error = svc_board.edit(data)
        if not error:
            return jsonify({'status': 200, 'message': 'Success', 'redirect': '/board'})
    if error:
        return jsonify({'status': 500, 'message': 'Error'})
    
    return render_template('board/edit.html', board=board)
            
@bp.route('/delete/<int:board_id>', methods=['GET', 'POST'])
@login_required
def delete(board_id):
    error = ''
    todo, error = svc_board.get_by_id(board_id)

    if request.method == 'POST':
        _,error = svc_board.delete(board_id)
        if not error:
            return redirect(url_for('board.home'))

    if error:
        flash(error)

    return jsonify({'status': 200, 'redirect': '/'})

tigrmanagr/controllers/todo.py
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, jsonify, session
from functools import wraps


import tigrmanagr.services.todo as svc_todo
import tigrmanagr.services.board as svc_board

bp = Blueprint('todo', __name__, url_prefix='/todo')


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        user = dict(session).get('profile', None)

        if user:
            return f(*args, **kwargs)
        return redirect('/login')
    return decorated_function

@bp.route('/edit/<int:todo_id>', methods=['GET', 'POST'])
@login_required
def edit(todo_id):
    error = ''
    todo, error = svc_todo.get_by_id(todo_id)

    if request.method == 'POST':
        title_update = request.form['title_update']
        status_update = request.form['status_update']

        data = {
            'todo_id': int(todo_id),
            'todo_title': title_update,
            'todo_status': status_update,
        }
        _,error = svc_todo.edit(data)
        if not error:
            return jsonify({'status': 200, 'message': 'Success', 'redirect': '/todo'})
    if error:
        return jsonify({'status': 500, 'message': 'Error'})
    
    return render_template('todo/edit.html', todo=todo)
            
@bp.route('/delete/<int:todo_id>', methods=['GET', 'POST'])
@login_required
def delete(todo_id):
    error = ''
    todo, error = svc_todo.get_by_id(todo_id)

    if request.method == 'POST':
        _,error = svc_todo.delete(todo_id)
        if not error:
            return redirect(url_for('board.home'))

    if error:
        flash(error)

    return jsonify({'status': 200, 'redirect': '/board'})

tigrmanagr/templates/board/create.html
{% extends "base.html" %}

{% block title %}
To Do
{% endblock %}

{% block content %}
    
    <input id="boardTitle" type="text" name="createBoard" placeholder="Input your Board name here">
    <button type="button" onclick="createBoard()">Create Board</button>
{% endblock %}

tigrmanagr/templates/board/edit.html
{% extends "base.html" %}

{% block title %}
To Do
{% endblock %}

{% block content %}
    
<div class="flex flex-col h-screen my-auto items-center">
    <div>
        <input type="text" id="boardEdit" value="{{ board.board_name }}">
    </div>
        <button type="button" onclick="updateBoard({{ board.board_id }})">Confirm Edit</button>
    </div>
</div>

{% endblock %}

tigrmanagr/templates/board/index.html
{% extends "base.html" %}

{% block title %}
To Do
{% endblock %}

{% block content %}
    <p class="text-right">Welcome, {{ email }}</p>
    <div class="-mt-8 w-fit h-full fixed bg-white-600 border">

        {% for board in boards %}
        <div class="mt-4">
            <a class="w-30 inline-flex ml-4 text-center text-lg font-bold" href="{{ url_for('board.boardSpace', board_id=board.board_id) }}">{{ board.board_name }}</a>
            <button class="float-right ml-4 inline-flex w-5 border bg-white-600 rounded-full" type="button" onclick="deleteBoard({{ board.board_id }}, {{ '\"%s\"' % board.board_name }})"><i class="fa fa-trash" aria-hidden="true"></i></button>
            <a class="float-right ml-10 inline-flex w-5 border bg-white-600 rounded-full" href="{{ url_for('board.edit', board_id=board.board_id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
        </div>
        {% endfor %}
        <div class="ml-4 mt-10"><a class="bg-green-500 text-white border rounded-md py-2 px-8" href="{{ url_for('board.createBoard') }}">Create</a></div>
    </div>

{% endblock %}

tigrmanagr/templates/board/read.html
{% extends "base.html" %}

{% block title %}
To Do
{% endblock %}

{% block content %}
    <p class="text-right">Welcome, {{ email }}</p>
    <div class="-mt-8 w-fit h-full fixed bg-white-600 border">

        {% for board in boards %}
        <div class="mt-4">
            <a class="w-30 inline-flex ml-4 text-center text-lg font-bold" href="{{ url_for('board.boardSpace', board_id=board.board_id) }}">{{ board.board_name }}</a>
            <button class="float-right ml-4 inline-flex w-5 border bg-white-600 rounded-full" type="button" onclick="deleteBoard({{ board.board_id }}, {{ '\"%s\"' % board.board_name }})"><i class="fa fa-trash" aria-hidden="true"></i></button>
            <a class="float-right ml-10 inline-flex w-5 border bg-white-600 rounded-full" href="{{ url_for('board.edit', board_id=board.board_id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
        </div>
        {% endfor %}
        <div class="ml-4 mt-10"><a class="bg-green-500 text-white border rounded-md py-2 px-8" href="{{ url_for('board.createBoard') }}">Create</a></div>
    </div>

    <table class="max-w-full mx-auto">
        <tr>
            <th class="text-center w-100 py-2 px-28 font-normal">Title</th>
            <th class="text-center w-100 py-2 px-28 font-normal">Status</th>
        </tr>

        {% for todo in todos %}
        <tr>
            <td id="title{{ todo.todo_id }}" class="border-solid border-l-4 border-t-2 border-slate-400 w-100 text-left text-stone-900 w-100 py-2 pl-7 pr-7">
                <div>
                    {{ todo.todo_title }}
                </div>
            </td>
            {% if todo.todo_status == 0 %}
                <td id="statustd{{ todo.todo_id }}" class="border-solid border-l-2 border-t-2 border-r-4 border-slate-400 w-100 text-center text-neutral-50 bg-red-600 py-2 px-28 todo">Todo</td>
            {% elif todo.todo_status == 1 %}         
                <td id="statustd{{ todo.todo_id }}" class="border-solid border-l-2 border-t-2 border-r-4 border-slate-400 w-100 text-center text-neutral-50 bg-yellow-400 py-2 px-28">Doing</td>            
            {% elif todo.todo_status == 2 %}         
                <td id="statustd{{ todo.todo_id }}" class="border-solid border-l-2 border-t-2 border-r-4 border-slate-400 w-100 text-center text-neutral-50 bg-green-500 py-2 px-28">Done</td>            
            {% endif %}
            <td id="editBtn"><a href="{{ url_for('todo.edit', todo_id=todo.todo_id)}}"><i class="fa fa-pencil ml-4" aria-hidden="true"></i></a></td>
            <td><button type="button" onclick="deleteTodo({{ todo.todo_id }}, {{ '\"%s\"' % todo.todo_title }})"><i class="fa fa-trash ml-10" aria-hidden="true"></i></button></td>
        </tr>
        {% endfor %}

        <tr class="bg-slate-100"> 
            <td class="border-solid border-l-4 border-t-2 border-r-4 border-b-2 border-slate-200 hover:border-green-400 w-100 text-left text-stone-400 hover:text-green-700 py-2 pl-7 pr-21" colspan="2" id="createTodo" ><a href="{{ url_for('board.createTodo', board_id=board.board_id) }}">Create</a></td>
        </tr>                                                                                                                    
    </table>

{% endblock %}